"""This module defines the Source class."""

from dataclasses import dataclass
from typing import Callable, Sequence

import jax.numpy as jnp
from scipy.constants import c, epsilon_0

from pycharge import potentials_and_fields
from pycharge.charge import Charge
from pycharge.types import Scalar, Vector3


@dataclass()
class Source:
    """A container for a dynamic electromagnetic source.

    This class bundles the initial state of a source's constituent charges
    with the ordinary differential equation (ODE) that governs its motion.
    It is used as input for the :func:`~pycharge.simulate.simulate` function.

    Attributes
    ----------
    charges_0 : Sequence[Charge]
        A sequence of ``Charge`` objects representing the initial state of the
        charges that make up the source.
    ode_func : Callable
        A function that defines the ODE for the source's dynamics. It should
        have the signature ``ode_func(t, u, other_charges)``, where ``t`` is
        the current time, ``u`` is the current state (positions and velocities),
        and ``other_charges`` is a list of all other charges in the simulation.

    """

    charges_0: Sequence[Charge]
    ode_func: Callable


def dipole_source(
    d_0: Vector3,
    q: float,
    omega_0: float,
    m: float,
    origin: Vector3,
) -> Source:
    """Factory for creating a dipole source that behaves as a Lorentz oscillator.

    This function creates a ``Source`` object representing a simple dipole,
    consisting of two opposite charges. The dipole's motion is governed by the
    driven harmonic oscillator equation, including a classical radiation damping
    term. It is designed to be used with the :func:`~pycharge.simulate.simulate`
    function.

    Parameters
    ----------
    d_0 : Vector3
        The initial displacement vector from the negative to the positive charge.
        This defines the initial dipole moment and the axis of polarization.
    q : float
        The magnitude of the charge for the positive particle (the other will have -q).
    omega_0 : float
        The natural angular frequency of the oscillator in rad/s.
    m : float
        The mass of each particle in the dipole. The effective mass of the
        oscillator will be m/2.
    origin : Vector3
        The center of mass of the dipole, which is assumed to be stationary.

    Returns
    -------
    Source
        A ``Source`` object ready to be used in a simulation.
    """
    d_0 = jnp.asarray(d_0)
    origin = jnp.asarray(origin)

    m_eff = m / 2
    gamma_0 = 1 / (4 * jnp.pi * epsilon_0) * 2 * q**2 * omega_0**2 / (3 * m_eff * c**3)
    polarization_direction = jnp.abs(d_0 / jnp.linalg.norm(d_0))

    positions_0 = [lambda t: origin - d_0 / 2, lambda t: origin + d_0 / 2]

    def dipole_ode_fn(t, u, other_charges):
        r0, v0 = u[0]
        r1, v1 = u[1]

        x, y, z = (r0 + r1) / 2
        E = potentials_and_fields(other_charges)(x, y, z, t).electric if other_charges else 0
        E = E * polarization_direction

        dipole_r = r1 - r0
        dipole_v = v1 - v0
        dipole_a = q / m_eff * E - gamma_0 * dipole_v - omega_0**2 * dipole_r

        dr0_dt, dv0_dt = v0, -dipole_a / 2
        dr1_dt, dv1_dt = v1, dipole_a / 2

        return jnp.array([[dr0_dt, dv0_dt], [dr1_dt, dv1_dt]])

    return Source(charges_0=(Charge(positions_0[0], -q), Charge(positions_0[1], q)), ode_func=dipole_ode_fn)


def free_particle_source(position_0: Callable[[Scalar], Vector3], q: float, m: float) -> Source:
    """Factory for creating a free particle source.

    This function creates a ``Source`` object representing a single free particle.
    The particle's motion is governed by the Lorentz force equation, where the
    electric and magnetic fields are generated by all other sources in the
    simulation. It is designed to be used with the
    :func:`~pycharge.simulate.simulate` function.

    Parameters
    ----------
    position_0 : Callable[[Scalar], Vector3]
        A function that defines the initial position of the particle at time t=0.
        Note that this function is only used to get the initial state; the
        trajectory is then determined by the simulation.
    q : float
        The electric charge of the particle in Coulombs.
    m : float
        The mass of the particle in kilograms.

    Returns
    -------
    Source
        A ``Source`` object ready to be used in a simulation.
    """

    def free_particle_ode_fn(t, u, other_charges):
        r, v = u[0]
        x, y, z = r

        quantities = potentials_and_fields(other_charges)(x, y, z, t) if other_charges else None
        E = quantities.electric if quantities else jnp.zeros(3)
        B = quantities.magnetic if quantities else jnp.zeros(3)

        dr_dt = v
        dv_dt = q / m * (E + jnp.cross(v, B))

        return jnp.array([[dr_dt, dv_dt]])

    return Source(charges_0=(Charge(position_0, q),), ode_func=free_particle_ode_fn)
