"""
Coupled Dipole Simulation
=========================

This example demonstrates how to simulate the coupled dynamics of two Lorentz
oscillators (dipoles). When dipoles are placed in close proximity, their
interaction modifies their radiative properties, leading to phenomena like
superradiance and subradiance.

In PyCharge, we can model this by creating multiple ``Source`` objects and
passing them to the ``simulate`` function. The simulation will self-consistently
solve for the motion of each charge as it is influenced by the fields
generated by all other charges in the system.

Here, we simulate two dipoles separated by 80 nm. We will then plot the
energy of the system over time to observe the collective decay.
"""

# %%
# 1. Import necessary libraries
# -----------------------------
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from scipy.constants import e, m_e

from pycharge import dipole_source, simulate

# %%
# 2. Define Simulation Parameters
# -------------------------------
# We'll define the physical properties of our dipoles and the simulation time.
# The two dipoles are identical and separated along the x-axis. They are
# both initialized with a small displacement along the z-axis.

# Physical parameters
separation = 80e-9  # Distance between dipoles along x-axis
initial_displacement = [0.0, 0.0, 1e-11]  # Initial charge separation
omega_0 = 100e12 * 2 * jnp.pi  # Natural angular frequency

# Simulation time
t_num = 20_000
dt = 1e-18
ts = jnp.linspace(0, (t_num - 1) * dt, t_num)

# %%
# 3. Create the Dipole Sources
# ----------------------------
# We create two ``dipole_source`` objects. The first is at the origin, and the
# second is displaced by `separation` along the x-axis.

dipole1 = dipole_source(
    d_0=initial_displacement,
    q=e,
    omega_0=omega_0,
    m=m_e,
    origin=[0.0, 0.0, 0.0],
)

dipole2 = dipole_source(
    d_0=initial_displacement,
    q=e,
    omega_0=omega_0,
    m=m_e,
    origin=[separation, 0.0, 0.0],
)

# We will also create an identical, isolated dipole to compare its decay rate.
isolated_dipole = dipole_source(
    d_0=initial_displacement,
    q=e,
    omega_0=omega_0,
    m=m_e,
    origin=[0.0, 0.0, 0.0],
)


# %%
# 4. Set Up and Run the Simulations
# ---------------------------------
# We create two separate simulations: one for the coupled system and one for the
# single, isolated dipole for comparison.

# JIT-compile the simulation functions for performance
sim_coupled_fn = jax.jit(simulate([dipole1, dipole2], ts))
sim_isolated_fn = jax.jit(simulate([isolated_dipole], ts))

# Run the simulations
print("Running coupled dipole simulation...")
coupled_states = sim_coupled_fn()
print("Running isolated dipole simulation...")
isolated_state = sim_isolated_fn()
print("Simulations complete.")

# %%
# 5. Analyze and Plot the Results
# -------------------------------
# We can analyze the dynamics by looking at the energy of the dipoles over time.
# The total energy of a Lorentz oscillator is the sum of its kinetic and
# potential energy.


def calculate_energy(state, source, ts):
    """Helper function to calculate the energy of a dipole over time."""
    # Extract position and velocity history for all charges in the source
    # Shape: (time, charges, {pos,vel}, {x,y,z})
    pos_history = state[:, :, 0, :]
    vel_history = state[:, :, 1, :]

    # Get properties from the source object
    m_eff = m_e / 2  # Effective mass for a two-charge system with equal mass
    omega_0 = source.ode_func.__closure__[2].cell_contents  # A bit of a hack to get omega_0

    # Calculate dipole displacement and velocity
    # For a two-charge source, dipole displacement is (pos_charge2 - pos_charge1)
    dipole_r = pos_history[:, 1, :] - pos_history[:, 0, :]
    dipole_v = vel_history[:, 1, :] - vel_history[:, 0, :]

    # Energy = 0.5 * m * v^2 + 0.5 * m * omega_0^2 * x^2
    kinetic_energy = 0.5 * m_eff * jnp.linalg.norm(dipole_v, axis=-1) ** 2
    potential_energy = 0.5 * m_eff * omega_0**2 * jnp.linalg.norm(dipole_r, axis=-1) ** 2
    return kinetic_energy + potential_energy


# Calculate energy for the coupled system (we'll just look at the first dipole)
energy_coupled = calculate_energy(coupled_states[0], dipole1, ts)

# Calculate energy for the isolated system
energy_isolated = calculate_energy(isolated_state[0], isolated_dipole, ts)

# Normalize the energy
energy_coupled /= energy_coupled.max()
energy_isolated /= energy_isolated.max()

# %%
# The plot below shows the normalized energy of one of the coupled dipoles
# compared to an identical isolated dipole. The coupled dipole exhibits a
# faster decay rate, a signature of superradiance.

plt.figure(figsize=(10, 6))
plt.plot(ts, energy_coupled, label="Coupled Dipole")
plt.plot(ts, energy_isolated, label="Isolated Dipole", linestyle="--")
plt.yscale("log")
plt.xlabel("Time (s)")
plt.ylabel("Normalized Energy")
plt.title("Energy Decay of Coupled vs. Isolated Dipoles")
plt.legend()
plt.grid(True)
plt.show()
